// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwtsxECnJi3MwLBv8Aa2nRLpAVoTK7STs',
    appId: '1:82695156984:web:cf3ca9d1d6ffea98fbf70d',
    messagingSenderId: '82695156984',
    projectId: 'kitchenguard-8e288',
    authDomain: 'kitchenguard-8e288.firebaseapp.com',
    storageBucket: 'kitchenguard-8e288.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyC3-EJFx69wdtftOPNHlCbtnkQsp8RDQ',
    appId: '1:82695156984:android:dcfc89a216792162fbf70d',
    messagingSenderId: '82695156984',
    projectId: 'kitchenguard-8e288',
    storageBucket: 'kitchenguard-8e288.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfYVaOHsCkU5qwrRoCYoQvi8QgaGPfLng',
    appId: '1:82695156984:ios:698255f9cea307f3fbf70d',
    messagingSenderId: '82695156984',
    projectId: 'kitchenguard-8e288',
    storageBucket: 'kitchenguard-8e288.firebasestorage.app',
    iosBundleId: 'com.kitchenguard.app',
  );

}